# Generated by Django 3.1.1 on 2021-01-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_auto_20210109_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participate',
        ),
    ]
