from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static 
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('regsuper', views.regsuper, name="regsuper"),
    path('regorg', views.regorg, name="regorg"),
    path('', views.home, name="home"),
    path('login/', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('about', views.about, name="about"),
    path('blog', views.blog, name="blog"),
    path('contact', views.contact, name="contact"),
    path('event', views.event, name="event"),
    path('notice', views.notice, name="notice"),
    path('signup', views.signup, name="signup"),
    path('user/<int:id>', views.userprofile, name="detail"),
    path('user/edit/<int:id>', views.userprofileedit, name="update"),
    path('user/edit/UploadPhoto/<int:id>', views.userprofileedit2, name="update2"),
    path('event/details/<int:id>', views.event_detail, name="event_detail"),
    path('resource', views.resource, name="resource"),
    path('previous', views.previous, name="previous"),
    path('session/<active_session>', views.session, name="session"),
    path('user/payment', views.payment, name="payment"),
    path('user/payment/request', views.payment2, name="payment2"),
    path('orgadmin', views.orgadmin, name="orgadmin"),
    path('orgadmin/<int:id>/addpay', views.addfund, name="addpay"),
    path('orgadmin/<int:id>/reject', views.Reject, name="reject"),
    path('addnotice', views.addnotice, name="addnotice"),
    path('notice/deletenotice/<id>', views.deletenotice, name="deletenotice"),
    path('notice/editnotice/<id>', views.editnotice, name="editnotice"),
    path('notice/updatenotice/<id>', views.editnotice, name="updatenotice"),
    path('addevent', views.addevent, name="addevent"),
    path('event/edit/<id>', views.editevent, name="editevent"),
    path('event/update/<id>', views.editevent, name="updateevent"),
    path('event/deleteevent/<id>', views.deleteevent, name="deleteevent"),
    path('event/photo/update/<id>', views.eventphoto, name="eventphoto"),
    path('notice/photo/update/<id>', views.noticephoto, name="noticephoto"),
    path('orgadmin_fund', views.fundview, name="fundview"),
    path('orgadmin_setting', views.settingview, name="settingview"),
    path('orgadmin_message', views.messageview, name="messageview"),
    path('contact', views.contact, name="contact"),
    path('orgadmin_carousel', views.carousel, name="carouselview"),
    path('addcarousel', views.addcarousel, name="addcarousel"),
    path('carouselON/<id>', views.carouselON, name="carouselON"),
    path('carouselOFF/<id>', views.carouselOFF, name="carouselOFF"),
    path('carouselDelete/<id>', views.carouselDelete, name="carouselDelete"),
    path('orgadmin_gallery', views.galleryview, name="galleryview"),
    path('orgadmin_gallery/change/<id>', views.photosEdit, name="photosEdit"),
    path('orgadmin_gallery/delete/<id>', views.photosOFF, name="photosdelete"),
    path('orgadmin_executive', views.executiveview, name="executiveview"),
    path('save_photo', views.save_photo, name="save_photo"),
    path('photos', views.photos, name="photos"),
    path('photos/<category>', views.viewphoto, name="viewphoto"),
    path('participate/<id>', views.participate, name="participate"),
    path('resource/<file_type>', views.file, name="file"),
    path('resource/<file_type>/<file_tag>', views.tagged, name="tagged"),
    path('designation_add', views.add_designation, name="add_designation"),
    path('del_about/<id>', views.delete_about, name="delete_about"),
    path('designation/<id>', views.edit_designation, name="editdesignation"),
    path('designation/delete/<id>', views.save_designation, name="deletedesignation"),
    #path('reset_password/', auth_views.PasswordResetView.as_view()),
    #path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view()),
    #path('reset/<uidb64>/<token>/', auth_views.password_reset_confirm.as_view(name="password_reset_confirm")),
    #path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view()),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
